package org.spa.model.discount;
// Generated 2016-5-12 11:49:54 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DiscountAttribute generated by hbm2java
 */
@Entity
@Table(name = "DISCOUNT_ATTRIBUTE", catalog = "loccitane")
public class DiscountAttribute implements java.io.Serializable {

    private Long id;
    private DiscountAttributeKey discountAttributeKey;
    private DiscountRule discountRule;
    private String value;
    private boolean isActive;
    private Date created;
    private String createdBy;
    private Date lastUpdated;
    private String lastUpdatedBy;

    public DiscountAttribute() {
    }

    public DiscountAttribute(DiscountAttributeKey discountAttributeKey, DiscountRule discountRule, String value, boolean isActive, Date created, String createdBy, Date lastUpdated, String lastUpdatedBy) {
        this.discountAttributeKey = discountAttributeKey;
        this.discountRule = discountRule;
        this.value = value;
        this.isActive = isActive;
        this.created = created;
        this.createdBy = createdBy;
        this.lastUpdated = lastUpdated;
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "discount_attribute_key_id", nullable = false)
    public DiscountAttributeKey getDiscountAttributeKey() {
        return this.discountAttributeKey;
    }

    public void setDiscountAttributeKey(DiscountAttributeKey discountAttributeKey) {
        this.discountAttributeKey = discountAttributeKey;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "discount_rule_id", nullable = false)
    public DiscountRule getDiscountRule() {
        return this.discountRule;
    }

    public void setDiscountRule(DiscountRule discountRule) {
        this.discountRule = discountRule;
    }

    @Column(name = "value", nullable = false)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Column(name = "is_active", nullable = false)
    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "created_by", nullable = false, length = 100)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_updated", nullable = false, length = 19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Column(name = "last_updated_by", nullable = false, length = 100)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

}
