<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@include file="/WEB-INF/jsp/common/jspInit.jsp"%>

<option value="KG"><spring:message code="label.country.KG" /></option>
<option value="LA"><spring:message code="label.country.LA" /></option>
<option value="LV"><spring:message code="label.country.LV" /></option>
<option value="LB"><spring:message code="label.country.LB" /></option>
<option value="LS"><spring:message code="label.country.LS" /></option>
<option value="LR"><spring:message code="label.country.LR" /></option>
<option value="LY"><spring:message code="label.country.LY" /></option>
<option value="LI"><spring:message code="label.country.LI" /></option>
<option value="LT"><spring:message code="label.country.LT" /></option>
<option value="LU"><spring:message code="label.country.LU" /></option>
<option value="MO"><spring:message code="label.country.MO" /></option>
<option value="MK"><spring:message code="label.country.MK" /></option>
<option value="MG"><spring:message code="label.country.MG" /></option>
<option value="MW"><spring:message code="label.country.MW" /></option>
<option value="MY"><spring:message code="label.country.MY" /></option>
<option value="MV"><spring:message code="label.country.MV" /></option>
<option value="ML"><spring:message code="label.country.ML" /></option>
<option value="MT"><spring:message code="label.country.MT" /></option>
<option value="MH"><spring:message code="label.country.MH" /></option>
<option value="MQ"><spring:message code="label.country.MQ" /></option>
<option value="MR"><spring:message code="label.country.MR" /></option>
<option value="MU"><spring:message code="label.country.MU" /></option>
<option value="YT"><spring:message code="label.country.YT" /></option>
<option value="MX"><spring:message code="label.country.MX" /></option>
<option value="FM"><spring:message code="label.country.FM" /></option>
<option value="MD"><spring:message code="label.country.MD" /></option>
<option value="MC"><spring:message code="label.country.MC" /></option>
<option value="MN"><spring:message code="label.country.MN" /></option>
<option value="MS"><spring:message code="label.country.MS" /></option>
<option value="MA"><spring:message code="label.country.MA" /></option>
<option value="MZ"><spring:message code="label.country.MZ" /></option>
<option value="MM"><spring:message code="label.country.MM" /></option>
<option value="NA"><spring:message code="label.country.NA" /></option>
<option value="NR"><spring:message code="label.country.NR" /></option>
<option value="NP"><spring:message code="label.country.NP" /></option>
<option value="AN"><spring:message code="label.country.AN" /></option>
<option value="NL"><spring:message code="label.country.NL" /></option>
<option value="NC"><spring:message code="label.country.NC" /></option>
<option value="NZ"><spring:message code="label.country.NZ" /></option>
<option value="NI"><spring:message code="label.country.NI" /></option>
<option value="NE"><spring:message code="label.country.NE" /></option>
<option value="NG"><spring:message code="label.country.NG" /></option>
<option value="NU"><spring:message code="label.country.NU" /></option>
<option value="NF"><spring:message code="label.country.NF" /></option>
<option value="MP"><spring:message code="label.country.MP" /></option>
<option value="NO"><spring:message code="label.country.NO" /></option>
<option value="OM"><spring:message code="label.country.OM" /></option>
<option value="PK"><spring:message code="label.country.PK" /></option>
<option value="PW"><spring:message code="label.country.PW" /></option>
<option value="PS"><spring:message code="label.country.PS" /></option>
<option value="PA"><spring:message code="label.country.PA" /></option>
<option value="PG"><spring:message code="label.country.PG" /></option>
<option value="PY"><spring:message code="label.country.PY" /></option>
<option value="PE"><spring:message code="label.country.PE" /></option>
<option value="PH"><spring:message code="label.country.PH" /></option>
<option value="PN"><spring:message code="label.country.PN" /></option>
<option value="PL"><spring:message code="label.country.PL" /></option>
<option value="PT"><spring:message code="label.country.PT" /></option>
<option value="PR"><spring:message code="label.country.PR" /></option>
<option value="QA"><spring:message code="label.country.QA" /></option>
<option value="RE"><spring:message code="label.country.RE" /></option>
<option value="RO"><spring:message code="label.country.RO" /></option>
<option value="RU"><spring:message code="label.country.RU" /></option>
<option value="RW"><spring:message code="label.country.RW" /></option>
<option value="SH"><spring:message code="label.country.SH" /></option>
<option value="KN"><spring:message code="label.country.KN" /></option>
<option value="LC"><spring:message code="label.country.LC" /></option>
<option value="PM"><spring:message code="label.country.PM" /></option>
<option value="VC"><spring:message code="label.country.VC" /></option>
<option value="WS"><spring:message code="label.country.WS" /></option>
<option value="SM"><spring:message code="label.country.SM" /></option>
<option value="ST"><spring:message code="label.country.ST" /></option>
<option value="SA"><spring:message code="label.country.SA" /></option>
<option value="SN"><spring:message code="label.country.SN" /></option>
<option value="CS"><spring:message code="label.country.CS" /></option>
<option value="SC"><spring:message code="label.country.SC" /></option>
<option value="SL"><spring:message code="label.country.SL" /></option>
<option value="SG"><spring:message code="label.country.SG" /></option>
<option value="SK"><spring:message code="label.country.SK" /></option>
<option value="SI"><spring:message code="label.country.SI" /></option>
<option value="SB"><spring:message code="label.country.SB" /></option>
<option value="SO"><spring:message code="label.country.SO" /></option>
<option value="ZA"><spring:message code="label.country.ZA" /></option>
<option value="GS"><spring:message code="label.country.GS" /></option>
<option value="ES"><spring:message code="label.country.ES" /></option>
<option value="LK"><spring:message code="label.country.LK" /></option>
<option value="SD"><spring:message code="label.country.SD" /></option>
<option value="SR"><spring:message code="label.country.SR" /></option>
<option value="SJ"><spring:message code="label.country.SJ" /></option>
<option value="SZ"><spring:message code="label.country.SZ" /></option>
<option value="SE"><spring:message code="label.country.SE" /></option>
<option value="CH"><spring:message code="label.country.CH" /></option>
<option value="SY"><spring:message code="label.country.SY" /></option>
<option value="TW"><spring:message code="label.country.TW" /></option>
<option value="TJ"><spring:message code="label.country.TJ" /></option>
<option value="TZ"><spring:message code="label.country.TZ" /></option>
<option value="TH"><spring:message code="label.country.TH" /></option>
<option value="TL"><spring:message code="label.country.TL" /></option>
<option value="TG"><spring:message code="label.country.TG" /></option>
<option value="TK"><spring:message code="label.country.TK" /></option>
<option value="TO"><spring:message code="label.country.TO" /></option>
<option value="TT"><spring:message code="label.country.TT" /></option>
<option value="TN"><spring:message code="label.country.TN" /></option>
<option value="TR"><spring:message code="label.country.TR" /></option>
<option value="TM"><spring:message code="label.country.TM" /></option>
<option value="TC"><spring:message code="label.country.TC" /></option>
<option value="TV"><spring:message code="label.country.TV" /></option>
<option value="VI"><spring:message code="label.country.VI" /></option>
<option value="UG"><spring:message code="label.country.UG" /></option>
<option value="UA"><spring:message code="label.country.UA" /></option>
<option value="AE"><spring:message code="label.country.AE" /></option>
<option value="GB"><spring:message code="label.country.GB" /></option>
<option value="UM"><spring:message code="label.country.UM" /></option>
<option value="US"><spring:message code="label.country.US" /></option>
<option value="UY"><spring:message code="label.country.UY" /></option>
<option value="UZ"><spring:message code="label.country.UZ" /></option>
<option value="VU"><spring:message code="label.country.VU" /></option>
<option value="VE"><spring:message code="label.country.VE" /></option>
<option value="VN"><spring:message code="label.country.VN" /></option>
<option value="WF"><spring:message code="label.country.WF" /></option>
<option value="EH"><spring:message code="label.country.EH" /></option>
<option value="YE"><spring:message code="label.country.YE" /></option>
<option value="ZM"><spring:message code="label.country.ZM" /></option>
<option value="ZW"><spring:message code="label.country.ZW" /></option>