<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@include file="/WEB-INF/jsp/common/jspInit.jsp"%>

<option value="AF"><spring:message code="label.country.AF" /></option>
<option value="AL"><spring:message code="label.country.AL" /></option>
<option value="DZ"><spring:message code="label.country.DZ" /></option>
<option value="AS"><spring:message code="label.country.AS" /></option>
<option value="AD"><spring:message code="label.country.AD" /></option>
<option value="AO"><spring:message code="label.country.AO" /></option>
<option value="AI"><spring:message code="label.country.AI" /></option>
<option value="AQ"><spring:message code="label.country.AQ" /></option>
<option value="AG"><spring:message code="label.country.AG" /></option>
<option value="AR"><spring:message code="label.country.AR" /></option>
<option value="AM"><spring:message code="label.country.AM" /></option>
<option value="AW"><spring:message code="label.country.AW" /></option>
<option value="AU"><spring:message code="label.country.AU" /></option>
<option value="AT"><spring:message code="label.country.AT" /></option>
<option value="AZ"><spring:message code="label.country.AZ" /></option>
<option value="BS"><spring:message code="label.country.BS" /></option>
<option value="BH"><spring:message code="label.country.BH" /></option>
<option value="BD"><spring:message code="label.country.BD" /></option>
<option value="BB"><spring:message code="label.country.BB" /></option>
<option value="BY"><spring:message code="label.country.BY" /></option>
<option value="BE"><spring:message code="label.country.BE" /></option>
<option value="BZ"><spring:message code="label.country.BZ" /></option>
<option value="BJ"><spring:message code="label.country.BJ" /></option>
<option value="BM"><spring:message code="label.country.BM" /></option>
<option value="BT"><spring:message code="label.country.BT" /></option>
<option value="BO"><spring:message code="label.country.BO" /></option>
<option value="BA"><spring:message code="label.country.BA" /></option>
<option value="BW"><spring:message code="label.country.BW" /></option>
<option value="BV"><spring:message code="label.country.BV" /></option>
<option value="BR"><spring:message code="label.country.BR" /></option>
<option value="IO"><spring:message code="label.country.IO" /></option>
<option value="VG"><spring:message code="label.country.VG" /></option>
<option value="BN"><spring:message code="label.country.BN" /></option>
<option value="BG"><spring:message code="label.country.BG" /></option>
<option value="BF"><spring:message code="label.country.BF" /></option>
<option value="BI"><spring:message code="label.country.BI" /></option>
<option value="KH"><spring:message code="label.country.KH" /></option>
<option value="CM"><spring:message code="label.country.CM" /></option>
<option value="CA"><spring:message code="label.country.CA" /></option>
<option value="CV"><spring:message code="label.country.CV" /></option>
<option value="KY"><spring:message code="label.country.KY" /></option>
<option value="CF"><spring:message code="label.country.CF" /></option>
<option value="TD"><spring:message code="label.country.TD" /></option>
<option value="CL"><spring:message code="label.country.CL" /></option>
<option value="CN"><spring:message code="label.country.CN" /></option>
<option value="CX"><spring:message code="label.country.CX" /></option>
<option value="CC"><spring:message code="label.country.CC" /></option>
<option value="CO"><spring:message code="label.country.CO" /></option>
<option value="KM"><spring:message code="label.country.KM" /></option>
<option value="CD"><spring:message code="label.country.CD" /></option>
<option value="CG"><spring:message code="label.country.CG" /></option>
<option value="CK"><spring:message code="label.country.CK" /></option>
<option value="CR"><spring:message code="label.country.CR" /></option>
<option value="CI"><spring:message code="label.country.CI" /></option>
<option value="CU"><spring:message code="label.country.CU" /></option>
<option value="CY"><spring:message code="label.country.CY" /></option>
<option value="CZ"><spring:message code="label.country.CZ" /></option>
<option value="DK"><spring:message code="label.country.DK" /></option>
<option value="DJ"><spring:message code="label.country.DJ" /></option>
<option value="DM"><spring:message code="label.country.DM" /></option>
<option value="DO"><spring:message code="label.country.DO" /></option>
<option value="EC"><spring:message code="label.country.EC" /></option>
<option value="EG"><spring:message code="label.country.EG" /></option>
<option value="SV"><spring:message code="label.country.SV" /></option>
<option value="GQ"><spring:message code="label.country.GQ" /></option>
<option value="ER"><spring:message code="label.country.ER" /></option>
<option value="EE"><spring:message code="label.country.EE" /></option>
<option value="ET"><spring:message code="label.country.ET" /></option>
<option value="FO"><spring:message code="label.country.FO" /></option>
<option value="FK"><spring:message code="label.country.FK" /></option>
<option value="FJ"><spring:message code="label.country.FJ" /></option>
<option value="FI"><spring:message code="label.country.FI" /></option>
<option value="FR"><spring:message code="label.country.FR" /></option>
<option value="GF"><spring:message code="label.country.GF" /></option>
<option value="PF"><spring:message code="label.country.PF" /></option>
<option value="TF"><spring:message code="label.country.TF" /></option>
<option value="GA"><spring:message code="label.country.GA" /></option>
<option value="GM"><spring:message code="label.country.GM" /></option>
<option value="GE"><spring:message code="label.country.GE" /></option>
<option value="DE"><spring:message code="label.country.DE" /></option>
<option value="GH"><spring:message code="label.country.GH" /></option>
<option value="GI"><spring:message code="label.country.GI" /></option>
<option value="GR"><spring:message code="label.country.GR" /></option>
<option value="GL"><spring:message code="label.country.GL" /></option>
<option value="GD"><spring:message code="label.country.GD" /></option>
<option value="GP"><spring:message code="label.country.GP" /></option>
<option value="GU"><spring:message code="label.country.GU" /></option>
<option value="GT"><spring:message code="label.country.GT" /></option>
<option value="GN"><spring:message code="label.country.GN" /></option>
<option value="GW"><spring:message code="label.country.GW" /></option>
<option value="GY"><spring:message code="label.country.GY" /></option>
<option value="HT"><spring:message code="label.country.HT" /></option>
<option value="HM"><spring:message code="label.country.HM" /></option>
<option value="VA"><spring:message code="label.country.VA" /></option>
<option value="HN"><spring:message code="label.country.HN" /></option>
<option value="HK"><spring:message code="label.country.HK" /></option>
<option value="HR"><spring:message code="label.country.HR" /></option>
<option value="HU"><spring:message code="label.country.HU" /></option>
<option value="IS"><spring:message code="label.country.IS" /></option>
<option value="IN"><spring:message code="label.country.IN" /></option>
<option value="ID"><spring:message code="label.country.ID" /></option>
<option value="IR"><spring:message code="label.country.IR" /></option>
<option value="IQ"><spring:message code="label.country.IQ" /></option>
<option value="IE"><spring:message code="label.country.IE" /></option>
<option value="IL"><spring:message code="label.country.IL" /></option>
<option value="IT"><spring:message code="label.country.IT" /></option>
<option value="JM"><spring:message code="label.country.JM" /></option>
<option value="JP"><spring:message code="label.country.JP" /></option>
<option value="JO"><spring:message code="label.country.JO" /></option>
<option value="KZ"><spring:message code="label.country.KZ" /></option>
<option value="KE"><spring:message code="label.country.KE" /></option>
<option value="KI"><spring:message code="label.country.KI" /></option>
<option value="KP"><spring:message code="label.country.KP" /></option>
<option value="KR"><spring:message code="label.country.KR" /></option>
<option value="KW"><spring:message code="label.country.KW" /></option>