package org.spa.model.bonus;
// Generated 2016-11-2 15:37:29 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.spa.model.company.Company;

/**
 * BonusTemplate generated by hbm2java
 */
@Entity
@Table(name = "BONUS_TEMPLATE", catalog = "loccitane")
public class BonusTemplate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Company company;
	private String name;
	private String description;
	private String content;
	private boolean isActive;
	private Date created;
	private String createdBy;
	private Date lastUpdated;
	private String lastUpdatedBy;
	private Set<BonusAttributeKey> bonusAttributeKeys = new HashSet<BonusAttributeKey>(0);
	private Set<BonusRule> bonusRules = new HashSet<BonusRule>(0);
	
	public BonusTemplate() {
	}

	public BonusTemplate(Company company, String name, String content, boolean isActive, Date created, String createdBy,
			Date lastUpdated, String lastUpdatedBy) {
		this.company = company;
		this.name = name;
		this.content = content;
		this.isActive = isActive;
		this.created = created;
		this.createdBy = createdBy;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public BonusTemplate(Company company, String name, String description, String content, boolean isActive,
			Date created, String createdBy, Date lastUpdated, String lastUpdatedBy,Set<BonusRule> bonusRules,
			Set<BonusAttributeKey> bonusAttributeKeys) {
		this.company = company;
		this.name = name;
		this.description = description;
		this.content = content;
		this.isActive = isActive;
		this.created = created;
		this.createdBy = createdBy;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
		this.bonusAttributeKeys = bonusAttributeKeys;
		this.bonusRules=bonusRules;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "content", nullable = false, length = 65535)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "is_active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by", nullable = false, length = 100)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bonusTemplate", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<BonusAttributeKey> getBonusAttributeKeys() {
		return this.bonusAttributeKeys;
	}

	public void setBonusAttributeKeys(Set<BonusAttributeKey> bonusAttributeKeys) {
		this.bonusAttributeKeys = bonusAttributeKeys;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bonusTemplate")
	public Set<BonusRule> getBonusRules() {
		return this.bonusRules;
	}

	public void setBonusRules(Set<BonusRule> bonusRules) {
		this.bonusRules = bonusRules;
	}
}
