package org.spa.model.payroll;
// Generated 2016-6-16 12:32:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StaffPayrollAttributeStatistics generated by hbm2java
 */
@Entity
@Table(name = "STAFF_PAYROLL_ATTRIBUTE_STATISTICS", catalog = "loccitane")
public class StaffPayrollAttributeStatistics implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private PayrollAttributeKey payrollAttributeKey;
	private StaffPayroll staffPayroll;
	private String value;

	public StaffPayrollAttributeStatistics() {
	}

	public StaffPayrollAttributeStatistics(PayrollAttributeKey payrollAttributeKey, StaffPayroll staffPayroll) {
		this.payrollAttributeKey = payrollAttributeKey;
		this.staffPayroll = staffPayroll;
	}

	public StaffPayrollAttributeStatistics(PayrollAttributeKey payrollAttributeKey, StaffPayroll staffPayroll,
			String value) {
		this.payrollAttributeKey = payrollAttributeKey;
		this.staffPayroll = staffPayroll;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payroll_attribute_key_id", nullable = false)
	public PayrollAttributeKey getPayrollAttributeKey() {
		return payrollAttributeKey;
	}
	public void setPayrollAttributeKey(PayrollAttributeKey payrollAttributeKey) {
		this.payrollAttributeKey = payrollAttributeKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staff_payroll_id", nullable = false)
	public StaffPayroll getStaffPayroll() {
		return this.staffPayroll;
	}

	public void setStaffPayroll(StaffPayroll staffPayroll) {
		this.staffPayroll = staffPayroll;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
