package org.spa.model.payroll;
// Generated 2016-9-21 12:31:53 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StaffPayrollAdditional generated by hbm2java
 */
@Entity
@Table(name = "STAFF_PAYROLL_ADDITIONAL", catalog = "loccitane")
public class StaffPayrollAdditional implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private StaffPayroll staffPayroll;
	private String label;
	private String value;
	private String type;
	
	public StaffPayrollAdditional() {
	}

	public StaffPayrollAdditional(StaffPayroll staffPayroll, String label, String value,String type) {
		this.staffPayroll = staffPayroll;
		this.label = label;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staff_payroll_id", nullable = false)
	public StaffPayroll getStaffPayroll() {
		return this.staffPayroll;
	}

	public void setStaffPayroll(StaffPayroll staffPayroll) {
		this.staffPayroll = staffPayroll;
	}

	@Column(name = "label", nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	@Column(name = "type", nullable = false)
	public String getType() {
		return type;
	}
	public void setType(String type) {
		this.type = type;
	}
}
