package org.spa.model.payroll;
// Generated 2016-6-16 12:32:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.spa.model.product.Category;

/**
 * StaffPayrollCategoryStatistics generated by hbm2java
 */
@Entity
@Table(name = "STAFF_PAYROLL_CATEGORY_STATISTICS", catalog = "loccitane")
public class StaffPayrollCategoryStatistics implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Category category;
	private StaffPayroll staffPayroll;
	private Double salesStatistics;
	private Double commissionStatistics;
	private Double bonusStatistics;
	private String bonusType;
	private Double targetAmount;
	
	public StaffPayrollCategoryStatistics() {
	}

	public StaffPayrollCategoryStatistics(Category category, StaffPayroll staffPayroll) {
		this.category = category;
		this.staffPayroll = staffPayroll;
	}

	public StaffPayrollCategoryStatistics(Category category, StaffPayroll staffPayroll, Double salesStatistics,
			Double commissionStatistics,Double bonusStatistics,String bonusType,Double targetAmount) {
		this.category = category;
		this.staffPayroll = staffPayroll;
		this.salesStatistics = salesStatistics;
		this.commissionStatistics = commissionStatistics;
		this.bonusStatistics=bonusStatistics;
		this.bonusType=bonusType;
		this.targetAmount=targetAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staff_payroll_id", nullable = false)
	public StaffPayroll getStaffPayroll() {
		return this.staffPayroll;
	}

	public void setStaffPayroll(StaffPayroll staffPayroll) {
		this.staffPayroll = staffPayroll;
	}

	@Column(name = "sales_statistics", precision = 22, scale = 0)
	public Double getSalesStatistics() {
		return this.salesStatistics;
	}

	public void setSalesStatistics(Double salesStatistics) {
		this.salesStatistics = salesStatistics;
	}

	@Column(name = "commission_statistics", precision = 22, scale = 0)
	public Double getCommissionStatistics() {
		return this.commissionStatistics;
	}

	public void setCommissionStatistics(Double commissionStatistics) {
		this.commissionStatistics = commissionStatistics;
	}

	@Column(name = "bonus_statistics", precision = 22, scale = 0)
	public Double getBonusStatistics() {
		return bonusStatistics;
	}
	public void setBonusStatistics(Double bonusStatistics) {
		this.bonusStatistics = bonusStatistics;
	}
	
	@Column(name = "bonus_type", length = 45)
	public String getBonusType() {
		return bonusType;
	}
	public void setBonusType(String bonusType) {
		this.bonusType = bonusType;
	}
	
	@Column(name = "target_amount", precision = 22, scale = 0)
	public Double getTargetAmount() {
		return targetAmount;
	}
	public void setTargetAmount(Double targetAmount) {
		this.targetAmount = targetAmount;
	}
}
