package org.spa.model.book;
// Generated 2017-1-17 17:18:21 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.spa.model.product.ProductOption;

/**
 * BookFirstStepRecord generated by hbm2java
 */
@Entity
@Table(name = "BOOK_FIRST_STEP_RECORD", catalog = "loccitane")
public class BookFirstStepRecord implements java.io.Serializable {

    private Long id;
    private Book book;
    private ProductOption productOption;
    private int guestAmount;
    private boolean shareRoom;
    private String startTime;
    private String endTime;
    private int displayOrder;
    
    /**
     * 是否有效.
     */
    private boolean isActive;

    /**
     * 创建时间.
     */
    private Date created;

    /**
     * 创建者.
     */
    private String createdBy;

    /**
     * 更新时间.
     */
    private Date lastUpdated;

    /**
     * 更新者.
     */
    private String lastUpdatedBy;

    private Long bundleId;
    
    public BookFirstStepRecord() {
    }

    public BookFirstStepRecord(Book book, ProductOption productOption, int guestAmount, boolean shareRoom, String startTime, String endTime, int displayOrder, boolean isActive, Date created, String createdBy, Date lastUpdated, String lastUpdatedBy) {
        this.book = book;
        this.productOption = productOption;
        this.guestAmount = guestAmount;
        this.shareRoom = shareRoom;
        this.startTime = startTime;
        this.endTime = endTime;
        this.displayOrder = displayOrder;
        this.isActive = isActive;
        this.created = created;
        this.createdBy = createdBy;
        this.lastUpdated = lastUpdated;
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "book_id", nullable = false)
    public Book getBook() {
        return this.book;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_option_id", nullable = false)
    public ProductOption getProductOption() {
        return this.productOption;
    }

    public void setProductOption(ProductOption productOption) {
        this.productOption = productOption;
    }

    @Column(name = "guest_amount", nullable = false)
    public int getGuestAmount() {
        return this.guestAmount;
    }

    public void setGuestAmount(int guestAmount) {
        this.guestAmount = guestAmount;
    }

    @Column(name = "share_room", nullable = false)
    public boolean isShareRoom() {
        return this.shareRoom;
    }

    public void setShareRoom(boolean shareRoom) {
        this.shareRoom = shareRoom;
    }

    @Column(name = "start_time", nullable = false, length = 45)
    public String getStartTime() {
        return this.startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    @Column(name = "end_time", nullable = false, length = 45)
    public String getEndTime() {
        return this.endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    @Column(name = "display_order", nullable = false)
    public int getDisplayOrder() {
        return this.displayOrder;
    }

    public void setDisplayOrder(int displayOrder) {
        this.displayOrder = displayOrder;
    }

    @Column(name = "is_active", nullable = false)
    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "created_by", nullable = false, length = 100)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_updated", nullable = false, length = 19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Column(name = "last_updated_by", nullable = false, length = 100)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
    
    @Column(name = "bundle_id")
	public Long getBundleId() {
		return bundleId;
	}
	public void setBundleId(Long bundleId) {
		this.bundleId = bundleId;
	}
}
