package org.spa.model.book;
// Generated 2016-11-2 10:06:25 by Hibernate Tools 4.3.1

import org.spa.model.user.User;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * BookItemTherapist generated by hbm2java
 */
@Entity
@Table(name = "BOOK_ITEM_THERAPIST", catalog = "loccitane")
public class BookItemTherapist implements java.io.Serializable {

    private Long id;
    private BookItem bookItem;

    /**
     * user id表示为技师.
     */
    private User user;
    private Boolean onRequest;

    public BookItemTherapist() {
    }

    public BookItemTherapist(BookItem bookItem, User user) {
        this.bookItem = bookItem;
        this.user = user;
    }

    public BookItemTherapist(BookItem bookItem, User user, Boolean onRequest) {
        this.bookItem = bookItem;
        this.user = user;
        this.onRequest = onRequest;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "book_item_id", nullable = false)
    public BookItem getBookItem() {
        return this.bookItem;
    }

    public void setBookItem(BookItem bookItem) {
        this.bookItem = bookItem;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "on_request")
    public Boolean getOnRequest() {
        return this.onRequest;
    }

    public void setOnRequest(Boolean onRequest) {
        this.onRequest = onRequest;
    }

}
