package org.spa.vo.sales;
// Generated 2018-1-18 15:50:45 by Hibernate Tools 4.3.1.Final

import org.spa.model.order.ReviewRatingShop;
import org.spa.model.prepaid.Prepaid;
import org.spa.vo.page.Page;

import java.util.Date;

/**
 * Coment generated by hbm2java
 */

public class ReviewRatingShopVO extends Page<ReviewRatingShop>implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Long reviewId;
	private Long shopId;
	private Integer customerServiceStar;
	private Integer cleanlinessStar;
	private boolean isActive;
	private Date created;
	private String createdBy;
	private Date lastUpdated;
	private String lastUpdatedBy;
	private String fromDate;
	private String toDate;

	public String getToDate() {
		return toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}

	public String getFromDate() {
		return fromDate;
	}

	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getReviewId() {
		return reviewId;
	}

	public void setReviewId(Long reviewId) {
		this.reviewId = reviewId;
	}

	public Long getShopId() {
		return shopId;
	}

	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	public Integer getCustomerServiceStar() {
		return customerServiceStar;
	}

	public void setCustomerServiceStar(Integer customerServiceStar) {
		this.customerServiceStar = customerServiceStar;
	}

	public Integer getCleanlinessStar() {
		return cleanlinessStar;
	}

	public void setCleanlinessStar(Integer cleanlinessStar) {
		this.cleanlinessStar = cleanlinessStar;
	}

	public boolean isActive() {
		return isActive;
	}

	public void setActive(boolean active) {
		isActive = active;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getLastUpdated() {
		return lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}
}
