package org.spa.model.version;
// Generated 2016-4-11 10:58:58 by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "version_control", catalog = "loccitane")
public class VersionControl implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private Long id;
    private String type;
    private String name;
    private double versionCode;
    private String description;
    private String url;
    private boolean isActive;
    private Date created;
    private String createdBy;
    private String size;
    public VersionControl() {
    }

    public VersionControl(String name, String type, boolean isActive) {
        this.name = name;
        this.type = type;
        this.isActive = isActive;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "type", nullable = false)
    public String getType() {
        return type;
    }
    public void setType(String type) {
        this.type = type;
    }



    @Column(name = "name", nullable = false)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

   @Column(name = "version_code", nullable = false, precision = 10)
    public double getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(double versionCode) {
        this.versionCode = versionCode;
    }


    @Column(name = "description", length =200 )
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "url", length =200 )
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    @Column(name = "is_active", nullable = false)
    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created",length = 19)
    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "created_by", length = 100)
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Column(name = "size", length =50 )
    public String getSize() {
        return size;
    }
    public void setSize(String size) {
        this.size = size;
    }
}
