package org.spa.model.order;
// Generated 2018-1-18 15:50:45 by Hibernate Tools 4.3.1.Final

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.spa.model.user.User;

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Coment generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "REVIEW_RATING_TREATMENT_THERAPIST", catalog = "loccitane")
public class ReviewRatingTreatmentTherapist implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private ReviewRatingTreatment reviewRatingTreatment;
	private User staff;
	private Integer staffStar;
	private boolean isActive;
	private Date created;
	private String createdBy;
	private Date lastUpdated;
	private String lastUpdatedBy;
	public ReviewRatingTreatmentTherapist() {
	}
	public ReviewRatingTreatmentTherapist(boolean isActive) {
		this.isActive = isActive;
	}

	public ReviewRatingTreatmentTherapist(long id,ReviewRatingTreatment reviewRatingTreatment, User staff, Integer staffStar,  boolean isActive, Date created, String createdBy,
										  Date lastUpdated, String lastUpdatedBy) {
		this.id=id;
		this.reviewRatingTreatment = reviewRatingTreatment;
		this.staff=staff;
		this.staffStar = staffStar;
		this.isActive = isActive;
		this.created = created;
		this.createdBy = createdBy;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "review_rating_treatment_id")
	public ReviewRatingTreatment getReviewRatingTreatment() {
		return this.reviewRatingTreatment;
	}

	public void setReviewRatingTreatment(ReviewRatingTreatment reviewRatingTreatment) {
		this.reviewRatingTreatment = reviewRatingTreatment;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staff_id",nullable = false)
	public User getStaff() {
		return this.staff;
	}

	public void setStaff(User staff) {
		this.staff = staff;
	}

	@Column(name = "staff_star", nullable = false)
	public Integer getStaffStar() {
		return this.staffStar;
	}

	public void setStaffStar(Integer staffStar) {
		this.staffStar = staffStar;
	}

	@Column(name = "is_active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by", length = 100)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
