package com.spa.drl
import  org.spa.model.discount.DiscountRule;
import com.spa.plugin.discount.DiscountItemAdapter;
import java.math.BigDecimal;

global org.slf4j.Logger logger;

rule " percentage off discount"
    when
        $discountRule : DiscountRule()
        $discountItemAdapter: DiscountItemAdapter(amount >= new BigDecimal($discountRule.getDiscountAttribute("TARGET_AMOUNT")));

    then
        BigDecimal itemAmount =  $discountItemAdapter.getAmount();
        BigDecimal percentageOff = new BigDecimal($discountRule.getDiscountAttribute("PERCENTAGE_OFF"));
        BigDecimal discountValue= itemAmount.multiply(percentageOff).divide(new BigDecimal("100"), 6, BigDecimal.ROUND_HALF_UP);
        $discountItemAdapter.setDiscountValue(discountValue);
        System.out.println("$discountItemAdapter discount11:" + $discountItemAdapter.getDiscountValue());
        logger.debug("itemAmount:{}, percentageOff:{}, discountValue:{}", itemAmount, percentageOff, discountValue);
end