package org.spa.model.commission;
// Generated 2016-7-25 15:13:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CommissionAttribute generated by hbm2java
 */
@Entity
@Table(name = "COMMISSION_ATTRIBUTE", catalog = "loccitane")
public class CommissionAttribute implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private CommissionAttributeKey commissionAttributeKey;
	private CommissionRule commissionRule;
	private String value;
	private boolean isActive;
	private Date created;
	private String createdBy;
	private Date lastUpdated;
	private String lastUpdatedBy;

	public CommissionAttribute() {
	}

	public CommissionAttribute(CommissionAttributeKey commissionAttributeKey, CommissionRule commissionRule,
			String value, boolean isActive, Date created, String createdBy, Date lastUpdated, String lastUpdatedBy) {
		this.commissionAttributeKey = commissionAttributeKey;
		this.commissionRule = commissionRule;
		this.value = value;
		this.isActive = isActive;
		this.created = created;
		this.createdBy = createdBy;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commission_attribute_key_id", nullable = false)
	public CommissionAttributeKey getCommissionAttributeKey() {
		return this.commissionAttributeKey;
	}

	public void setCommissionAttributeKey(CommissionAttributeKey commissionAttributeKey) {
		this.commissionAttributeKey = commissionAttributeKey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "commission_rule_id", nullable = false)
	public CommissionRule getCommissionRule() {
		return this.commissionRule;
	}

	public void setCommissionRule(CommissionRule commissionRule) {
		this.commissionRule = commissionRule;
	}

	@Column(name = "value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "is_active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", nullable = false, length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by", nullable = false, length = 100)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

}
