package org.spa.model.marketing;
// Generated 2016-5-31 17:46:31 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.spa.model.Document;
import org.spa.model.company.Company;

/**
 * MktMailShot generated by hbm2java
 */
@Entity
@Table(name = "MKT_MAIL_SHOT", catalog = "loccitane")
public class MktMailShot implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
    private Company company;
    private Document document;
    private MktChannel mktChannel;
    private String reference;
    private String type;
    private String userIds;
    private String subject;
    private String content;
    private Date sendTime;
    private int sendAmount;
    private String remarks;
    private String status;
    private boolean isActive;
    private Date created;
    private String createdBy;
    private Date lastUpdated;
    private String lastUpdatedBy;
    private Set<MktOutbox> mktOutboxes = new HashSet<MktOutbox>(0);

    public MktMailShot() {
    }

    public MktMailShot(Company company, MktChannel mktChannel, String reference, String type, String userIds, String subject, String content, Date sendTime, int sendAmount, String status, boolean isActive, Date created, String createdBy, Date lastUpdated, String lastUpdatedBy) {
        this.company = company;
        this.mktChannel = mktChannel;
        this.reference = reference;
        this.type = type;
        this.userIds = userIds;
        this.subject = subject;
        this.content = content;
        this.sendTime = sendTime;
        this.sendAmount = sendAmount;
        this.status = status;
        this.isActive = isActive;
        this.created = created;
        this.createdBy = createdBy;
        this.lastUpdated = lastUpdated;
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public MktMailShot(Company company, Document document, MktChannel mktChannel, String reference, String type, String userIds, String subject, String content, Date sendTime, int sendAmount, String remarks, String status, boolean isActive, Date created, String createdBy, Date lastUpdated, String lastUpdatedBy,
                       Set<MktOutbox> mktOutboxes) {
        this.company = company;
        this.document = document;
        this.mktChannel = mktChannel;
        this.reference = reference;
        this.type = type;
        this.userIds = userIds;
        this.subject = subject;
        this.content = content;
        this.sendTime = sendTime;
        this.sendAmount = sendAmount;
        this.remarks = remarks;
        this.status = status;
        this.isActive = isActive;
        this.created = created;
        this.createdBy = createdBy;
        this.lastUpdated = lastUpdated;
        this.lastUpdatedBy = lastUpdatedBy;
        this.mktOutboxes = mktOutboxes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
    public Company getCompany() {
        return this.company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "document_id")
    public Document getDocument() {
        return this.document;
    }

    public void setDocument(Document document) {
        this.document = document;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "channel_id", nullable = false)
    public MktChannel getMktChannel() {
        return this.mktChannel;
    }

    public void setMktChannel(MktChannel mktChannel) {
        this.mktChannel = mktChannel;
    }

    @Column(name = "reference", nullable = false, length = 45)
    public String getReference() {
        return this.reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    @Column(name = "type", nullable = false, length = 45)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "user_ids", nullable = false, length = 65535)
    public String getUserIds() {
        return this.userIds;
    }

    public void setUserIds(String userIds) {
        this.userIds = userIds;
    }

    @Column(name = "subject", nullable = false)
    public String getSubject() {
        return this.subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    @Column(name = "content", nullable = false, length = 65535)
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "send_time", nullable = false, length = 19)
    public Date getSendTime() {
        return this.sendTime;
    }

    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    @Column(name = "send_amount", nullable = false)
    public int getSendAmount() {
        return this.sendAmount;
    }

    public void setSendAmount(int sendAmount) {
        this.sendAmount = sendAmount;
    }

    @Column(name = "remarks")
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "is_active", nullable = false)
    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "created_by", nullable = false, length = 100)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_updated", nullable = false, length = 19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Column(name = "last_updated_by", nullable = false, length = 100)
    public String getLastUpdatedBy() {
        return this.lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "mktMailShot")
    public Set<MktOutbox> getMktOutboxes() {
        return this.mktOutboxes;
    }

    public void setMktOutboxes(Set<MktOutbox> mktOutboxes) {
        this.mktOutboxes = mktOutboxes;
    }

}
