package org.spa.model.marketing;
// Generated 2016-5-31 17:46:31 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.spa.model.user.User;

/**
 * MktOutbox generated by hbm2java
 */
@Entity
@Table(name = "MKT_OUTBOX", catalog = "loccitane")
public class MktOutbox implements java.io.Serializable {

    private Long id;
    private MktMailShot mktMailShot;
    private User user;
    private String email;
    private String status;
    private String remark;
    private boolean isActive;
    private Date created;
    private String createdBy;

    public MktOutbox() {
    }

    public MktOutbox(MktMailShot mktMailShot, User user, String email, String status, boolean isActive, Date created, String createdBy) {
        this.mktMailShot = mktMailShot;
        this.user = user;
        this.email = email;
        this.status = status;
        this.isActive = isActive;
        this.created = created;
        this.createdBy = createdBy;
    }

    public MktOutbox(MktMailShot mktMailShot, User user, String email, String status, String remark, boolean isActive, Date created, String createdBy) {
        this.mktMailShot = mktMailShot;
        this.user = user;
        this.email = email;
        this.status = status;
        this.remark = remark;
        this.isActive = isActive;
        this.created = created;
        this.createdBy = createdBy;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "mkt_mail_shot_id", nullable = false)
    public MktMailShot getMktMailShot() {
        return this.mktMailShot;
    }

    public void setMktMailShot(MktMailShot mktMailShot) {
        this.mktMailShot = mktMailShot;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "email", nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "remark", length = 65535)
    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @Column(name = "is_active", nullable = false)
    public boolean isIsActive() {
        return this.isActive;
    }

    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "created_by", nullable = false, length = 100)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

}
