package org.spa.model.product;
// Generated 2016-3-31 15:50:45 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.spa.model.company.Company;

/**
 * ProductOptionKey generated by hbm2java
 */
@Entity
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "PRODUCT_OPTION_KEY", catalog = "loccitane")
public class ProductOptionKey implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Company company;
	private String name;
	private String reference;
	private String uiType;
	private String initOption;
    private String unit;
	private boolean isActive;
	private Date created;
	private String createdBy;
	private Date lastUpdated;
	private String lastUpdatedBy;
	private String defaultValue;
	
	private Boolean labelShow;
	
	private Set<ProductOptionAttribute> productOptionAttributes = new HashSet<ProductOptionAttribute>(0);
	private Set<Category> categories = new HashSet<Category>(0);

	
	public ProductOptionKey() {
	}

	public ProductOptionKey(String reference, boolean isActive) {
		this.reference = reference;
		this.isActive = isActive;
	}

    public ProductOptionKey(Company company, String name, String reference, String uiType, String initOption, String unit, boolean isActive, Date created, String createdBy, Date lastUpdated, String lastUpdatedBy, String defaultValue, Set<ProductOptionAttribute> productOptionAttributes, Set<Category> categories) {
        this.company = company;
        this.name = name;
        this.reference = reference;
        this.uiType = uiType;
        this.initOption = initOption;
        this.unit = unit;
        this.isActive = isActive;
        this.created = created;
        this.createdBy = createdBy;
        this.lastUpdated = lastUpdated;
        this.lastUpdatedBy = lastUpdatedBy;
        this.defaultValue = defaultValue;
        this.productOptionAttributes = productOptionAttributes;
        this.categories = categories;
    }


    @Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "reference", nullable = false, length = 50)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "UI_type", length = 45)
	public String getUiType() {
		return this.uiType;
	}

	public void setUiType(String uiType) {
		this.uiType = uiType;
	}

	@Column(name = "init_option")
	public String getInitOption() {
		return this.initOption;
	}

	public void setInitOption(String initOption) {
		this.initOption = initOption;
	}

    @Column(name = "unit", length = 45)
    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

	@Column(name = "is_active", nullable = false)
	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "created_by", length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by", length = 100)
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}
	
	@Column(name = "default_value", length = 255)
	public String getDefaultValue() {
		return defaultValue;
	}
	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}
	
	@OneToMany(fetch = FetchType.LAZY)
	public Set<ProductOptionAttribute> getProductOptionAttributes() {
		return this.productOptionAttributes;
	}

	public void setProductOptionAttributes(Set<ProductOptionAttribute> productOptionAttributes) {
		this.productOptionAttributes = productOptionAttributes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "product_option_key_category", catalog = "loccitane", joinColumns = {
			@JoinColumn(name = "product_option_key_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "category_id", nullable = false, updatable = false) })
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

	@Column(name = "label_show", nullable = false)
	public Boolean getLabelShow() {
		return labelShow;
	}
	
	public void setLabelShow(Boolean labelShow) {
		this.labelShow = labelShow;
	}
}
